<?php
// error_reporting( -1 );
// ini_set( 'display_errors', 1 );
// $wgShowExceptionDetails = true;
# This file was automatically generated by the MediaWiki 1.32.0-alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename =  [
    'default' => 'Dinopedia',
    'datawiki' => 'Dinopedia Data',
  ];

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = [
    'dinopedia' => 'https://dinopedia-uk.herokuapp.com',
    'datawiki' => 'https://dinopedia-uk.herokuapp.com',
  ];

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@dinopedia-uk.herokuapp.com";
$wgPasswordSender = "apache@dinopedia-uk.herokuapp.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
// $wgDBtype = "mysql";
// $wgDBserver = "us-cdbr-iron-east-01.cleardb.net";
// $wgDBname = "heroku_962d388bf837885";
// $wgDBuser = "b410cc586edf60";
// $wgDBpassword = "34b9f2be";

$url = parse_url(getenv("CLEARDB_DATABASE_URL"));

$wgDBtype = "mysql";
$wgDBserver = $url["host"];
$wgDBname = substr($url["path"], 1);
$wgDBuser = $url["user"];
$wgDBpassword = $url["pass"];

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "uk";

$wgSecretKey = getenv("SECRET_KEY");

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = getenv("UPGRADE_KEY");

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# End of automatically generated settings.
# Add more configuration options below.

wfLoadSkin('Vector');

# Wikibase
$wgEnableWikibaseRepo = true;
$wgEnableWikibaseClient = true;
require_once "$IP/extensions/Wikibase/repo/Wikibase.php";
require_once "$IP/extensions/Wikibase/repo/ExampleSettings.php";
require_once "$IP/extensions/Wikibase/client/WikibaseClient.php";
require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";

wfLoadExtension( 'ParserFunctions' );

wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'Gadgets' );

wfLoadExtension( 'Interwiki' );
$wgGroupPermissions['sysop']['interwiki'] = true;

wfLoadExtension( 'CodeEditor' );
$wgDefaultUserOptions['usebetatoolbar'] = 1;

wfLoadExtension( 'Cite' );

wfLoadExtension( 'Popups' );

wfLoadExtension( 'WikibaseCreateLink' );
$wgWBClientSettings['siteGlobalID'] = 'dinopedia';
$wgWBClientSettings['globalID'] = 'dinopedia';
if ( $wmgUseWikibaseRepo ) {
  $wgEnableWikibaseRepo = true;
  $wgContentHandlerUseDB = true;
  // Register extra namespaces.
  $wgExtraNamespaces[WB_NS_ITEM] = 'Item';
  $wgExtraNamespaces[WB_NS_ITEM_TALK] = 'Item_talk';
  $wgExtraNamespaces[WB_NS_PROPERTY] = 'Property';
  $wgExtraNamespaces[WB_NS_PROPERTY_TALK] = 'Property_talk';
  $wgWBRepoSettings['entityNamespaces'] = [
    'item' => WB_NS_ITEM,
    'property' => WB_NS_PROPERTY
  ];
  // Tell Wikibase which namespace to use for which kind of entity
  // Make sure we use the same keys on repo and clients, so we can share cached objects.
  // NOTE: no need to set up $wgNamespaceContentModels, Wikibase will do that automatically based on $wgWBRepoSettings
  // Tell MediaWIki to search the item namespace
  $wgNamespacesToBeSearchedDefault[WB_NS_ITEM] = true;
  // the special group includes all the sites in the specialSiteLinkGroups,
  // grouped together in a 'Pages linked to other sites' section.
  $wgWBRepoSettings['siteLinkGroups'] = [
    'dinopedia',
    'wikipedia',
    'special'
  ];
  // these are the site_group codes as listed in the sites table
  $wgWBRepoSettings['specialSiteLinkGroups'] = [ 'commons', 'wikidata' ];
  $wgWBRepoSettings['statementSections'] = [
    'item' => [
      'statements' => null,
      'identifiers' => [
        'type' => 'dataType',
        'dataTypes' => [ 'external-id' ],
      ],
    ],
  ];
  $wgWBRepoSettings['localClientDatabases'] = [
    'dinopedia' => 'dinopedia',
  ];
  $wgWBRepoSettings['formatterUrlProperty'] = 'P6';
  $wgContentNamespaces = array_merge( $wgContentNamespaces, [ WB_NS_ITEM, WB_NS_PROPERTY ] );
}
if ( $wmgUseWikibaseClient ) {
  $wgEnableWikibaseClient = true;
  $wgWBClientSettings['repoUrl'] = 'https://dinopedia-uk.herokuapp.com';
  $wgWBClientSettings['repoArticlePath'] = '/index.php?title=$1';
  $wgWBClientSettings['repoScriptPath'] = '/w';
  $wgWBClientSettings['repositories'] = [
    '' => [
      'repoDatabase' => 'datawiki',
      'baseUri' => $wgWBClientSettings['repoUrl'] . '/entity/',
      'entityNamespaces' => [
        'item' => WB_NS_ITEM,
                    'property' => WB_NS_PROPERTY
      ],
      'prefixMapping' => [ '' => '' ],
    ]
  ];
  $wgWBClientSettings['siteGlobalID'] = 'dinopedia';
  $wgWBClientSettings['siteGroup'] = 'dinopedia';
  $wgWBClientSettings['changesDatabase'] = 'datawiki';
  $wgWBCLientSettings['injectRecentChanges'] = true;
  $wgWBClientSettings['languageLinkSiteGroup'] = 'dinopedia';
  $wgWBClientSettings['repoNamespaces'] = [
    'item' => 'Item',
    'property' => 'Property',
  ];
  $wgWBClientSettings['entityNamespaces'] = [
    'item' => $wmgWikibaseBaseNs,
    'property' => $wmgWikibaseBaseNs + 2,
  ];

  $wgWBClientSettings['repoSiteName'] = 'dinopedia Data';
  $wgWBClientSettings['otherProjectsLinks'] = [ 'wikidatawiki', 'commonswiki', 'ukwiki', 'enwiki' ];
  $wgWBClientSettings['otherProjectsLinksByDefault'] = true;
  $wgWBClientSettings['sendEchoNotification'] = true;
  $wgHooks['WikibaseClientOtherProjectsSidebar'][] = function ( Wikibase\DataModel\Entity\ItemId $itemId, array &$sidebar ) {
    foreach ( $sidebar as $id => &$group ) {
      foreach ( $group as $siteId => &$attributes ) {
        if ( isset( $attributes['hreflang'] ) ) {
          $attributes['msg'] = $attributes['msg'] . '-' . $attributes['hreflang'];
        }
      }
    }
    return true;
  };
}
